#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SchoolMeals.Resource", IsApplication=true)]

namespace SchoolMeals
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050011
			public const int addOrEditCostButton = 2131034129;
			
			// aapt resource value: 0x7f05000f
			public const int addOrEditPupilButton = 2131034127;
			
			// aapt resource value: 0x7f050016
			public const int amount = 2131034134;
			
			// aapt resource value: 0x7f050015
			public const int amountLabel = 2131034133;
			
			// aapt resource value: 0x7f050009
			public const int cancel = 2131034121;
			
			// aapt resource value: 0x7f050001
			public const int datePicker1 = 2131034113;
			
			// aapt resource value: 0x7f05000e
			public const int edit = 2131034126;
			
			// aapt resource value: 0x7f050014
			public const int exit = 2131034132;
			
			// aapt resource value: 0x7f05000c
			public const int firstName = 2131034124;
			
			// aapt resource value: 0x7f050003
			public const int fullCostLabel = 2131034115;
			
			// aapt resource value: 0x7f05000d
			public const int isDiscount = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int lastName = 2131034123;
			
			// aapt resource value: 0x7f050002
			public const int linearLayout1 = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int linearLayout2 = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public const int menu = 2131034122;
			
			// aapt resource value: 0x7f050004
			public const int normalCost = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int oK = 2131034120;
			
			// aapt resource value: 0x7f050012
			public const int payCostButton = 2131034130;
			
			// aapt resource value: 0x7f050010
			public const int removePupilButton = 2131034128;
			
			// aapt resource value: 0x7f050000
			public const int scrollView1 = 2131034112;
			
			// aapt resource value: 0x7f050017
			public const int selectDate = 2131034135;
			
			// aapt resource value: 0x7f050013
			public const int setPresenceAndDiscountButton = 2131034131;
			
			// aapt resource value: 0x7f050007
			public const int withDiscount = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int withDiscountLabel = 2131034118;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddOrEditCost = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AddOrEditPupil = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Pay = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Presence = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int RemovePupil = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040004
			public const int add_or_edit_cost = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int add_or_edit_pupil = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int pay = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int remove_pupil = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int set_presence_and_discount = 2130968582;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
